#indicamos el lenguaje que estamos usando
language: node_js
#vamos a probar desde la versión 8 a la última
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - node
#esta sección se ejecuta antes de la instalación de la aplicación (antes de npm install . )
#instalamos Jest y Grunt
before_install:
  - npm install -g jest grunt
#ejecutamos los tests con grunt
script: grunt test
