version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: irenecj/proyecto-idiomas
    steps:
      - checkout
      - run:
          name: Ejecutar test
          command: |
            grunt test
workflows:
  testeo:
    jobs:
      - test
