version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  test:
    docker:
      - image: docker:18.06.1-ce-git
      - image: irenecj/proyecto-idiomas
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Ejecutar test
          command: |
            docker run -t -v `pwd`:/test irenecj/proyecto-idiomas
workflows:
  testeo:
    jobs:
      - test
