#versión de la plataforma circle que estamos usando
version: 2.1
orbs:
  node: circleci/node@1.1
#tareas que vamos a realizar
jobs:
  build:
    executor:
      name: node/default
      tag: '14.0'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install -g jest
            - run: npm install -g grunt
      - run: grunt test
