#versión de la plataforma circle que estamos usando
version: 2.1
orbs:
  node: circleci/node@1.1
#tareas que vamos a realizar
jobs:
  #nombre de la tarea
  build:
    executor:
      name: node/default
      tag: '14.0'
    #listado de órdenes a ejecutar
    steps:
      - checkout
      #almacenamos en caché automáticamente los paquetes
      - node/with-cache:
        #instalamos todo lo necesario
        steps:
          - run: npm install
          - run: sudo npm install -g jest grunt
      - run: grunt test
